### ISSUE TITLE
Fault Tolerance aspect

### ISSUE THREAD

**Issue by Muhtasham** [deepmind/alphatensor#1]
Dear Authors, 
First of all thanks for the great work and congrats on breakthrough! 

In the paper the Fault Tolerance aspect of multiplication algorithms are left out, could you please shed some light on it. I believe this has serious implications.

**Comment by Sciroccogti** [comment]
Isn't this an exact multiplication algorithms?

**Comment by matejbalog** [comment]
Thank you!

Yes, the algorithms in this work are exact.

For testing numerical precision when multiplying matrices of floats, you can see `benchmarking/test_correctness.py` and the metrics referenced in [Supplement](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-022-05172-4/MediaObjects/41586_2022_5172_MOESM1_ESM.pdf) B.3 of the paper
