### ISSUE TITLE
Where is the DRL training code? 

### ISSUE THREAD

**Issue by JiahaoYao** [deepmind/alphatensor#4]
I didn't find the sampled AlphaZero code in the repo? Could you direct me there?

**Comment by kitlith** [comment]
Are you looking for the supplementary information? https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-022-05172-4/MediaObjects/41586_2022_5172_MOESM1_ESM.pdf

**Comment by matejbalog** [comment]
Thanks for your interest. Unfortunately, the sampled AlphaZero code is not open sourced.
