### ISSUE TITLE
4x4x4 algorithm for real arithmetic?

### ISSUE THREAD

**Issue by a1880** [deepmind/alphatensor#5]
From your article, I was hoping to find an algorithm for the 4x4x4 case with 47 products.
However, the article presents a mod 2 algorithm. In your factorizations collection of real arithmetic algorithms, the 4x4x4 case has 49 products. Recursive application of the 2x2x2 Strassen algorithm also requires 49 products.

Do you actually have an algorithm which outperforms recursive Strassen for the general 4x4x4 case?

**Comment by AaronKel** [comment]
From the paper it is only 47 for the case of mod 2 over z2/n and is non-commutative. [Stothers' thesis](https://www.era.lib.ed.ac.uk/handle/1842/4734) allows for 48 multiplications.

**Comment by ValZapod** [comment]
>allows for 48 multiplications.

That is commutative and thus pretty useless.

**Comment by ValZapod** [comment]
In fact even their 2x2 algorithm is not optimal. Cause best optimal proved by Probert is 15 additions. Okay? Wow. 7 multiplications and 15 additions.

**Comment by ValZapod** [comment]
Apparently, this paper descrives why 47 mod 2 result cannot be used in normal arithmetic:

>One of the remarkable outcomes of the recent work of Fawzi et al. [8] is an apparent discrepancy of the rank depending on the characteristic of the ground field. Their scheme for (n,m,p) = (4,4,4) of rank 47 as well as their scheme for (n,m,p) = (5,5,5) of rank 96 are only valid in characteristic two and can be shown not to be the homomorphic image of a scheme for K = Q.

https://arxiv.org/abs/2212.01175
